name: course-python2
channels:
- conda-forge
dependencies:
- python=3.13
- ipython
- jupyter
- jupyterlab>=4
- numpy
- pandas=2.3
- matplotlib>3
- mplleaflet
- ipympl
- seaborn
- plotnine
- pyproj
- requests
- openpyxl
- geopandas
- pyarrow
