title = "Data manipulation, analysis and visualisation in Python"
organisation = "Transferable Skills course - Doctoral School of Ghent University"
dates = "19, 22 and 26 January 2026"
repository = "DS-python-data-analysis"
conda_environment = "DS-python"
hackmd = "https://hackmd.io/84p71jbvRheG6uz12h9ICg?both"
googleform = "https://forms.gle/J5i4VfCj8682sDjP7"